name: Validate HTML and JavaScript

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install dependencies
      run: npm install -g htmlhint jshint
      
    - name: Validate HTML
      run: htmlhint *.html
      
    - name: Validate JavaScript
      run: jshint *.js
